[package]
name = "graphql-benchmark"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "3.0.5"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
juniper = "0.15.7"
lazy_static = "1.4.0"
